name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome
          run: echo "Hello World"

        - name: List files
          run: ls